### ISSUE TITLE
Consider shorter reversed syntax

### ISSUE THREAD

**Issue by teamon** [monterail/git-way#1]
if I have branches: `fix/foo` and `feature/bar` I'd like to write

```
git stage bar
git stage foo
```

and git-way should figure out what I want to do. In case I have `fix/x` and `feature/x` branches git-way would require writing

```
git stage fix x
git stage feature x
```

**Comment by szajbus** [comment]
`git stage` is a built-in git command, it is a synonym for `git-add` :(

**Comment by szajbus** [comment]
And it is not possible to override built-in commands http://stackoverflow.com/questions/3538774/is-it-possible-to-override-git-command-by-git-alias

**Comment by szajbus** [comment]
How about `git way stage feature x`. It's longer but eliminates possible future issues with name collisions.

**Comment by sheerun** [comment]
Maybe leave git command alone and introduce only `way`.

**Comment by szajbus** [comment]
@sheerun I thought about it too and I like it. 

So there are two options:

`git way ...` if you want it to be a subcommand of git.
or just `way ...` if you want shorter syntax. 

both can be used at the same time.
